exclude: [
  'node_modules',
  'Gruntfile.js',
  'package.json',
  'bower.json',
  'bower_components',
  'suit_components',
  'components',
  'component.json',
  'README.md',
  'grunt'
  ]

permalink: /:year/:title.html
ftp_host: simonsmith.io
ftp_dir: /public_html/new
ftp_passive: false
ftp_username: 'simon'
markdown: rdiscount
